### ISSUE TITLE
Check-in dependency versions

### ISSUE THREAD

**Issue by bzz** [acleclair/ICPC2020_GNN#1]
Thank you for sharing the source code for your interesting paper!

To foster reproducibility, it would be nice to put `requirements.txt` into the repository as well, to avoid possible confusion.

**Comment by acleclair** [comment]
Thank you for the feedback. I have added a requirements.txt file to the repository.

**Comment by Guardian99** [comment]
How do you predict a single file? I have all the necessary files and pretrained models downloaded.
