### ISSUE TITLE
ValueError: Unknown layer: GCNLayer

### ISSUE THREAD

**Issue by rishab-32** [acleclair/ICPC2020_GNN#8]
Hi thanks for sharing the code, I have been trying to reproduce the results presented in the paper.

To do this I have trained the codegnnbilstm model from scratch using the instructions and code provided in the repository. The model trains fine. However, when I try to run the predict.py file, I run into the following error. 

ValueError: Unknown layer: GCNLayer

**Comment by TenzinJinpa2019** [comment]
hi I am trying to reproduce the code and I am constantly getting is error 

`Traceback (most recent call last):
  File "train.py", line 12, in <module>
    from utils.model import create_model
  File "/content/ICPC2020_GNN/utils/model.py", line 1, in <module>
    from models.codegnngru import CodeGNNGRU
  File "/content/ICPC2020_GNN/models/codegnngru.py", line 6, in <module>
    from tensorflow.keras.layers import CuDNNGRU
ImportError: cannot import name 'CuDNNGRU'`


Thank You

**Comment by acleclair** [comment]
When you load the model you may need to change keras.load_model({model file}, custom_objects=GCNLayer) and make sure you import GCNLayer

**Comment by rishab-32** [comment]
Hi, Thanks for your reply, I have the correct model and GCN layer imported in the file, however still I run into this error. I am using the exact same code provided in the repository. I am not able to understand the possible cause for the same.

from models.custom.graphlayer import GCNLayer)

keras.models.load_model(modelfile, custom_objects={"tf":tf, "keras":keras,'AlexGraphLayer':GCNLayer})

**Comment by yz1019117968** [comment]
I also encountered this problem, have you solved it?

**Comment by yz1019117968** [comment]
Sorry, I just solved it, just change the {"tf":tf, "keras":keras,'AlexGraphLayer':GCNLayer}) to custom_objects={"tf":tf, "keras":keras,'GCNLayer':GCNLayer}, then the network can recognize the customized GCNLayer
