### ISSUE TITLE
What is the difference between tdat and sdat？

### ISSUE THREAD

**Issue by ZhichaoOuyang** [acleclair/ICPC2020_GNN#9]
Hello~
What is the difference between tdat and sdat?
could the Readme be written more complete and how to use your model on other data sets?

**Comment by DRMALEK** [comment]
İ think that "tdat" file is for a methods and their id. However "sdat" file is for file context data, a group of methods that is in the same file for a method in tdat. 

You can take a look at their "Improved Automatic Summarization of Subroutines via Attention to File Context" paper to get a better understanding.

**Comment by ZhichaoOuyang** [comment]
> İ think that "tdat" file is for a methods and their id. However "sdat" file is for file context data, a group of methods that is in the same file for a method in tdat.
> 
> You can take a look at their "Improved Automatic Summarization of Subroutines via Attention to File Context" paper to get a better understanding.

ok! Thanks

**Comment by acleclair** [comment]
DRMALEK is correct. In the context of this paper we only use the tdat. The sdat are vector representations of the other methods within the same file to add file context for another similar project - "Improved Automatic Summarization of Subroutines via Attention to File Context" which DRMALEK mentioned above. The repo for that project can be found [here](https://github.com/Attn-to-FC/Attn-to-FC)
